### ISSUE TITLE
python manage.py createviewtable

### ISSUE THREAD

**Issue by mchesler613** [pyohei/django-view-table#14]
When I tried this command, I get the following error:
```
$ python manage.py createviewtable
Unknown command: 'createviewtable'. Did you mean createcachetable?
Type 'manage.py help' for usage.
```
Do I need to run Django 3.1 in order for this to work? Thanks.

**Comment by jk602a** [comment]
Please check installed app as follows.
INSTALLED_APPS=[
    'viewtable',    <-- view_table
]

**Comment by pyohei** [comment]
Thank you!
I will close this issue as resolved.
